/**
 * Common Types
 *
 * Shared type definitions used across the app.
 */

// Re-export API types
export * from '@services/api/types';

// App Types
export type ThemeMode = 'light' | 'dark' | 'auto';

export interface AppSettings {
  theme: ThemeMode;
  notifications: boolean;
  language: string;
}

export interface AppState {
  isLoading: boolean;
  error: string | null;
  settings: AppSettings;
}

// Navigation Types (will be auto-generated by expo-router)
export type RootStackParamList = {
  '(tabs)': undefined;
  modal: undefined;
};

export type TabParamList = {
  index: undefined;
  explore: undefined;
  profile: undefined;
};
