# EAS Build Custom Workflow - Development
#
# This workflow builds development versions with Expo Dev Client.
# Allows for rapid development and testing of native modules.
#
# Trigger: Manual

name: Development Build

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to build'
        required: true
        type: choice
        options:
          - all
          - ios
          - android

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Setup Expo
      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      # Step 5: Build development client
      - name: Build development client
        run: |
          eas build --profile development --platform ${{ inputs.platform }} --non-interactive --no-wait

      # Step 6: Notify completion
      - name: Notify
        run: |
          echo "Development build started for ${{ inputs.platform }}"
          echo "Install on device and connect to Metro bundler for development"
