# EAS Build Custom Workflow - Production
#
# This workflow builds production versions of both iOS and Android apps.
# It runs tests, linting, and type checking before building.
#
# Trigger: Manual or on release tag

name: Production Build

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to build'
        required: true
        type: choice
        options:
          - all
          - ios
          - android
      submit:
        description: 'Submit to stores after build'
        required: false
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Run linting
      - name: Run ESLint
        run: npm run lint

      # Step 5: Run type checking
      - name: Type check
        run: npm run type-check

      # Step 6: Run tests
      - name: Run tests
        run: npm test

      # Step 7: Setup Expo
      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      # Step 8: Build app
      - name: Build app
        run: |
          if [ "${{ inputs.platform }}" = "all" ]; then
            eas build --profile production --platform all --non-interactive --no-wait
          else
            eas build --profile production --platform ${{ inputs.platform }} --non-interactive --no-wait
          fi

      # Step 9: Submit to stores (optional)
      - name: Submit to stores
        if: ${{ inputs.submit }}
        run: |
          if [ "${{ inputs.platform }}" = "all" ] || [ "${{ inputs.platform }}" = "ios" ]; then
            eas submit --platform ios --latest --non-interactive
          fi
          if [ "${{ inputs.platform }}" = "all" ] || [ "${{ inputs.platform }}" = "android" ]; then
            eas submit --platform android --latest --non-interactive
          fi
